# Generated by Django 5.1 on 2025-02-03 06:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_App', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='custom_user',
            old_name='cinc',
            new_name='cnic',
        ),
        migrations.AlterField(
            model_name='custom_user',
            name='is_staff',
            field=models.BooleanField(default='True'),
        ),
    ]
