# Generated by Django 5.1 on 2025-01-28 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test_app', '0002_customuser_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='email',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='uname',
        ),
        migrations.RemoveField(
            model_name='customuser',
            name='user',
        ),
    ]
