# Generated by Django 5.1 on 2025-02-03 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Test_App', '0003_alter_custom_user_cnic_alter_custom_user_is_staff'),
    ]

    operations = [
        migrations.CreateModel(
            name='Files_uploaded',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('files', models.FileField(upload_to='')),
            ],
        ),
    ]
