# Generated by Django 5.1 on 2025-02-03 14:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Test_App', '0004_files_uploaded'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Files_uploaded',
        ),
    ]
